name: TreeCapitator
version: 1.0.0
main: com.treecapitator.TreeCapitator
api-version: '1.20'
description: Chop down entire trees by breaking one log block
author: YourName

permissions:
  treecapitator.use:
    description: Allows using treecapitator
    default: true
